[package]
name = "trackfwd"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
clap = { version = "4.5.58", features = ["derive"] }
openvr = "0.8.1"
rosc = "0.11.4"
